# Generated by Django 4.1.5 on 2023-01-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('invite_code', models.CharField(max_length=10)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.simpleuser')),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=16)),
                ('cvv2', models.CharField(max_length=4)),
                ('expire_date', models.DateField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.simpleuser')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='users',
            field=models.ManyToManyField(to='bank.simpleuser'),
        ),
    ]
